language: node_js
sudo: false
node_js:
- '0.10'
cache:
  directories:
  - node_modules
before_script:
- npm install -g grunt-cli
env:
  global:
  - SELENIUM_HOST=hub.browserstack.com
  - SELENIUM_PORT=80
  - BS_AUTOMATE_PROJECT="$TRAVIS_REPO_SLUG"
  - BS_AUTOMATE_BUILD="Travis build No. $TRAVIS_BUILD_NUMBER for $TRAVIS_REPO_SLUG"
  - secure: AIIthWLUAlwPCkEt6IRpheZUmXqJHh2n/6SC+WEBLzU9l2oCw/gaeRZFP3lKvAxSiPTNpXhXyknD7Y6cCCAX1fjw2t3qhy9yBVrwucQo/FsEsbwFw3ZBxzIbQYAsSnq2iQ6pAvCYcnE9iriYQu+VnUZabGeAjOZKx7ajH5k9edo=
  - secure: HIEWChVznK3FvyS1xiFCCd5ffzLpN7LHj7NAkR1bvFXi7sI2w+/kcKjl8wCd4eAm/SMk0liOhYPycym0BWfkkJWygEq77mJ0FhCvFj67vqOmXqawR9j6WKqGvhsUpQoJTgRfQdxdfuaYgxHx71bYzphFViZMRrdBnlvploEXtQ8=
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/7b309d0fef51b1696205
    on_success: always
    on_failure: always
    on_start: false
deploy:
  provider: npm
  email: andrewjdodson@gmail.com
  api_key:
    secure: ehiWCI/WzQzQpzWEslLKR2mUqwO99rU+8jo141pkhgHDv6yanD6+qNWeOt8H9qJv+6lm9eXjrPPUfybIE26cl/1Emrzbo0xgTI29xCFV+/OrIwsUHTK0npGJkhgOiCW1sO293P1SR4Iivr/JKtdp8weiUg3HC1mwx+K2YTpzVIw=
  'on':
    tags: true
    repo: MrSwitch/hello.js
    all_branches: true
